#!/usr/bin/env python

"""
Overkill Project Creator 0.0.1
Copyright (c) 2014 Samuel "MrOverkill" Meyers
"""

import os, sys

print "Overkill Project Creator 0.0.1"
print "Copyright (c) 2014 Samuel \"MrOverkill\" Meyers"
print ""

usage = "Usage: " + sys.argv[0] + " <projectname>"

argc = len(sys.argv)

if argc < 2:
  print usage
else:
  os.makedirs(sys.argv[1])
  os.chdir(sys.argv[1])
  os.makedirs("src")
  os.makedirs("out")
  os.makedirs("bin")
  os.chdir("src")
  f = open("main.cxx", "w")
  f.write("""/*
This file was created by Overkill Project Creator 0.0.1
Copyright (c) 2014 Samuel "MrOverkill" Meyers
*/

#include <iostream>

using namespace std;

int main(int argc, char* argv[])
{
  cout<<"Hello, World!"<<endl;
}""")
  f.close()
  os.chdir("..")
  f = open("Makefile", "w")
  f.write("""default:
	g++ -c src/main.cxx -o out/main.o
	g++ out/main.o -o bin/main.out""")
  f.close()
  print "Project created!"
  print "Building..."
  os.system("make")
  print "Succeeded!"
  print "Running..."
  os.system("./bin/main.out")
  print "Done!"
