#!/usr/bin/env python

import os, sys

"""
Overkill Project Creator 0.0.3
Copyright (c) 2014 Samuel "MrOverkill" Meyers
Unix setup
"""

if not os.path.exists("/usr/local/bin/makeproject"):
	os.system("cp src/makeproject /usr/local/bin/")
	os.system("chmod 777 /usr/local/bin/makeproject")

if not os.path.exists("/usr/local/opc"):
	os.system("mkdir /usr/local/opc")
	os.system("chmod -R 777 /usr/local/opc")

if not os.path.exists("/usr/local/opc/templates"):
	os.system("cp -rf templates /usr/local/opc/")
	os.system("chmod -R 777 /usr/local/opc/templates")

print "Installed"
